-- Enable UUID generation extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create 'audit_results' table
CREATE TABLE IF NOT EXISTS audit_results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tool TEXT NOT NULL,
    current_spend NUMERIC NOT NULL,
    recommended_action TEXT NOT NULL,
    savings NUMERIC NOT NULL,
    reason TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create 'leads' table
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    company_name TEXT,
    role TEXT,
    team_size INTEGER,
    audit_result_id UUID REFERENCES audit_results(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Configure Row Level Security (RLS)
-- For demonstration/assignment purposes, we enable public write and read access.
-- In production, you would restrict these access privileges.

ALTER TABLE audit_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (Insert & Select)
CREATE POLICY "Allow public insert to audit_results" ON audit_results FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select from audit_results" ON audit_results FOR SELECT USING (true);

CREATE POLICY "Allow public insert to leads" ON leads FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select from leads" ON leads FOR SELECT USING (true);
